### ISSUE TITLE
added final report

### ISSUE THREAD

**Issue by trevorkwan** [UBC-MDS/DSCI_522_Group_303#33]
hey team, i've completed the final report which includes (intro, analysis, figures and tables, results discussion, bibtex citations for all packages used), updated our proposal, and wrote a test function for analyze_data.py (not sure if the test function works), and have submitted a pull request

from my understanding, these are the things that need to be wrapped up
Add instructions to run the scripts on README.md
Create version2.0
Submit links

**Comment by moniquewong** [comment]
Updated list of to-do's remaining:
- [x] Update README.md for simplicity and script instructions (see instructions below)
- [x] Place updated project proposal in a separate file
- [x] On report: fix Table 2 rendering, reduce image size (right now it prints off as 7 pages because of large images), fix formatting (some bullet points were lost), add to narrative for analysis to reflect the flow / logic of selecting the final model
- [x] Ensure scripts are well-documented (comments throughout)
- [x] Ensure there is a test function **for each supporting function** in `analyze_data.py`
- [x] Clean up file directory to match [Tiffany's recommendations](https://github.com/ttimbers/breast_cancer_predictor)
- [ ] Create version 2.0
- [ ] Submit links

---
Instructions:
- In the main README.md file for this project you should explain the project in a short summary (view from 10,000 feet) and also explain how to run your data analysis (which order scripts are run in, what expected inputs are). Your explanation could include a flow chart/dependecy diagram. This should be an evolution of what was submitted at the proposal stage. *Yes, we are asking you to overwrite your proposal here, and so if you want to keep that in a more findable place than in the Git history, do create a new file in the doc directory to archive it there (e.g., proposal.md).
- Each individual script must be well documented. This means comments throughout, readable code and a brief summary at the top of each file that answers who wrote it, when it was written and what it does. Additionally, in your project's README.md file, explain how to reproducibly run your scripts from top to bottom, including the arguments that need to be provided to each script.
