### ISSUE TITLE
Create Makefile for project

### ISSUE THREAD

**Issue by moniquewong** [UBC-MDS/DSCI_522_Group_303#38]
- [ ] Create makefile with Lecture 5 instructions

**Comment by trevorkwan** [comment]
i've created the makefile with documentation, but am unable to run it because I am unable to run the selenium package on my laptop without chromedriver (which is quite a time consuming problem). I have not had the time to get this fixed yet, but so I have created a pull request with the Makefile and hopefully we can test it out on one of your comptuers tomorrow in lab.

**Comment by moniquewong** [comment]
I get this comment when I run it: 
make: Circular docs/final_report_milestone_2.Rmd <- docs/final_report_milestone_2.Rmd dependency dropped.

@trevorkwan Can you check what this means?

**Comment by trevorkwan** [comment]
@moniquewong yes, thanks!
