### ISSUE TITLE
Milestone 3 Peer Feedback

### ISSUE THREAD

**Issue by trevorkwan** [UBC-MDS/DSCI_522_Group_303#45]
1) suggest scaling numbers so that the MSE is more readable
2) the conclusion should clearly describe the final model of what features we should include and the model
3) you should set the airbnb price to the ones that are actually gettting booked, more important research question, differentiate which observations have a higher booking rate

-Feedback from Manuel and Zoe

**Comment by moniquewong** [comment]
Response to suggestion 2:
- This is included in the intro; no feature selection was done so the beginning features are the final features

Response to suggestion 3:
- This is not possible. Booking rates was not a part of the initial dataset. We also assume that in a competitive market that hosts are setting prices at market levels. Booking rate may not also be what we are optimizing for since optimal pricing is maximum profit which may involve lower than average booking rates at high prices.

**Comment by moniquewong** [comment]
Suggestion 1 addressed through update to report script that set the formatting of numerical tables through `Kable`
